name: igrow
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  
  # Firebase
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.5.0
  
  # Firebase UI (instead of google_sign_in)
  firebase_ui_auth: ^1.10.0
  firebase_ui_oauth_google: ^1.2.16
  
  # Data & Location
  geolocator: ^13.0.2
  http: ^1.3.0
  shared_preferences: ^2.2.2
  uuid: ^4.5.1   # Updated to resolve dependency conflict

  image_picker: ^1.0.4
  firebase_storage: ^12.4.3  # Updated to latest compatible version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/