// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3lgZElbKi6a-XFXWfWLmH-xp-203-jD0',
    appId: '1:606644287553:web:fea73807fdc647c842aec0',
    messagingSenderId: '606644287553',
    projectId: 'i-grow-25',
    authDomain: 'i-grow-25.firebaseapp.com',
    storageBucket: 'i-grow-25.firebasestorage.app',
    measurementId: 'G-0907NLR39R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfyBkx7Vub23MMVGLdL1rPXAJn37MpbwU',
    appId: '1:606644287553:android:d87681e4515a126a42aec0',
    messagingSenderId: '606644287553',
    projectId: 'i-grow-25',
    storageBucket: 'i-grow-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3FsJ_9Q108tevCbjSEALV7t1L7tbeiVU',
    appId: '1:606644287553:ios:c1b2b7c260e5848942aec0',
    messagingSenderId: '606644287553',
    projectId: 'i-grow-25',
    storageBucket: 'i-grow-25.firebasestorage.app',
    iosBundleId: 'com.example.igrow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3FsJ_9Q108tevCbjSEALV7t1L7tbeiVU',
    appId: '1:606644287553:ios:c1b2b7c260e5848942aec0',
    messagingSenderId: '606644287553',
    projectId: 'i-grow-25',
    storageBucket: 'i-grow-25.firebasestorage.app',
    iosBundleId: 'com.example.igrow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3lgZElbKi6a-XFXWfWLmH-xp-203-jD0',
    appId: '1:606644287553:web:eca412341310c67542aec0',
    messagingSenderId: '606644287553',
    projectId: 'i-grow-25',
    authDomain: 'i-grow-25.firebaseapp.com',
    storageBucket: 'i-grow-25.firebasestorage.app',
    measurementId: 'G-NTESPNCLJZ',
  );
}
